name: Test and Deploy Dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Deploy
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Push changes
        run: git push
